# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "4280d0b7-12d2-4295-8502-79e9a96a3270"

default_platform :android

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  # build the release variant
  gradle(task: "assembleRelease")

  # upload to Beta by Crashlytics
  crashlytics(
    api_token: "7a9da90345ae192fb6655168986efc0c2e819d91",
    build_secret: "29f0b8970264e384826283e0f0e81a5a58c11d4af733ee17257ee1ac165c5bf8",
    apk_path: "app/build/outputs/apk/app-release.apk"
  )
end
